language: java
jdk: oraclejdk8
install: true
script: mvn clean install
cache:
  directories:
  - $HOME/.m2
after_success:
  - mvn clean test jacoco:report
  - bash <(curl -s https://codecov.io/bash)
  
